OptionsWebSite/Controllers/ChoiceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DiplomaDataModel.Models;
using DotNet.Highcharts.Options;
using DotNet.Highcharts.Helpers;
using DotNet.Highcharts.Enums;
using DotNet.Highcharts;
using System.Drawing;

namespace OptionsWebSite.Controllers
{
    public class ChoiceController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Choice
        public ActionResult Index()
        {
            ViewBag.DefaultTerm = db.YearTerms
                .Where(yt => yt.IsDefault == true)
                .FirstOrDefault()
                .YearTermId;
            return View();
        }

        public ActionResult Modify()
        {
            return View(db.Choices.Include("Option1").Include("Option2").Include("Option3").Include("Option4").Include("YearTerm").ToList());
        }

        public PartialViewResult YearTermSelect()
        {
            ViewBag.YearTermList = new SelectList(
                db.YearTerms
                .GroupBy(yt => yt.YearTermId)
                .Select(y => y.FirstOrDefault())
                .OrderBy(y => !y.IsDefault),
                "YearTermId", "Description");
            return PartialView("_YearTermSelectPartial");

        }
        public PartialViewResult GenerateChartPartial(int yeartermid = 0)
        {
           
            ViewBag.DefaultTerm = db.YearTerms
                .Where(yt => yt.IsDefault == true)
                .FirstOrDefault()
                .YearTermId;

            int numOfOptions = db.Options
                .Where(o => o.IsActive == true)
                .Count();
            int numOfStudents = db.Choices
                .Where(c => c.YearTermId == yeartermid)
                .Count();

            int[] activeOptionIds = db.Options
                .Where(o => o.IsActive == true)
                .Select(ot => ot.OptionId)
                .ToArray();
            string[] optionsList = db.Options
                .Where(o => o.IsActive == true)
                .OrderBy(or => or.OptionId)
                .Select(ot => ot.Title)
                .ToArray();
            

            object[] firstOptionCount = new object[numOfOptions];
            object[] secondOptionCount = new object[numOfOptions];
            object[] thirdOptionCount = new object[numOfOptions];
            object[] fourthOptionCount = new object[numOfOptions];

            for (int i = 0; i < activeOptionIds.Length; i++)
            {
                var tempid = activeOptionIds[i];
                var temp = db.Choices
                    .Where(c => c.FirstChoiceOptionId == tempid
                            && c.YearTermId == yeartermid)
                    .Count();
                firstOptionCount[i] = temp;
            }

            for (int i = 0; i < activeOptionIds.Length; i++)
            {
                var tempid = activeOptionIds[i];
                var temp = db.Choices
                    .Where(c => c.SecondChoiceOptionId == tempid
                            && c.YearTermId == yeartermid)
                    .Count();
                secondOptionCount[i] = temp;
            }

            for (int i = 0; i < activeOptionIds.Length; i++)
            {
                var tempid = activeOptionIds[i];
                var temp = db.Choices
                    .Where(c => c.ThirdChoiceOptionId == tempid
                            && c.YearTermId == yeartermid)
                    .Count();
                thirdOptionCount[i] = temp;
            }

            for (int i = 0; i < activeOptionIds.Length; i++)
            {
                var tempid = activeOptionIds[i];
                var temp = db.Choices
                    .Where(c => c.FourthChoiceOptionId == tempid
                            && c.YearTermId == yeartermid)
                    .Count();
                fourthOptionCount[i] = temp;
            }

            Highcharts chart = new Highcharts("chart")
                .InitChart(new Chart { DefaultSeriesType = ChartTypes.Column })
                .SetTitle(new Title { Text = "Student Option Selections " })
                .SetXAxis(new XAxis { Categories = optionsList })
                .SetYAxis(new YAxis
                {
                    Min = 0,
                    Title = new YAxisTitle { Text = "Students" }
                })
                .SetPlotOptions(new PlotOptions
                {
                    Column = new PlotOptionsColumn
                    {
                        PointPadding = 0.2,
                        BorderWidth = 0
                    }
                })
                .SetSeries(new[]
                {
                    new Series { Name = "First Choice", Data = new Data(firstOptionCount) },
                    new Series { Name = "Second Choice", Data = new Data(secondOptionCount) },
                    new Series { Name = "Third Choice", Data = new Data(thirdOptionCount) },
                    new Series { Name = "Fourth Choice", Data = new Data(fourthOptionCount) },
                });

            return PartialView("_ChartReportPartial", chart);
        }
        public PartialViewResult GenerateReportPartial(int yeartermid = 0)
        {

            ViewBag.Message = yeartermid;
            return PartialView("_DetailReportPartial", db.Choices
                .Include("Option1")
                .Include("Option2")
                .Include("Option3")
                .Include("Option4")
                .Include("YearTerm")
                .ToList());
        }

        public ActionResult Details(int? id)
        // GET: Choice/Details/5
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // Choice choice = db.Choices.Find(id);

            Choice choice = db.Choices.Include("Option1").Include("Option2").Include("Option3").Include("Option4").Include("YearTerm").FirstOrDefault(c => c.ChoiceId == id);
            if (choice == null)
            {
                return HttpNotFound();
            }
            return View(choice);
        }

        // GET: Choice/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Choice/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ChoiceId,StudentId,StudentFirstName,StudentLastName,FirstChoiceOptionId,SecondChoiceOptionId,ThirdChoiceOptionId,FourthChoiceOptionId,SelectionDate,YearTerm")] Choice choice)
        {

            if (ModelState.IsValid)
            {
                db.Choices.Add(choice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(choice);
        }

        // GET: Choice/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Choice choice = db.Choices.Find(id);
            if (choice == null)
            {
                return HttpNotFound();
            }
            return View(choice);
        }

        // POST: Choice/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ChoiceId,StudentId,StudentFirstName,StudentLastName,FirstChoiceOptionId,SecondChoiceOptionId,ThirdChoiceOptionId,FourthChoiceOptionId,SelectionDate,YearTerm")] Choice choice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(choice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(choice);
        }

        // GET: Choice/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Choice choice = db.Choices.Find(id);
            if (choice == null)
            {
                return HttpNotFound();
            }
            return View(choice);
        }

        // POST: Choice/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Choice choice = db.Choices.Find(id);
            db.Choices.Remove(choice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OptionsWebSite/Views/Choice/Create.cshtml
@model DiplomaDataModel.Models.Choice

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Choice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentFirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentLastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstChoiceOptionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstChoiceOptionId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstChoiceOptionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecondChoiceOptionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecondChoiceOptionId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecondChoiceOptionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThirdChoiceOptionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThirdChoiceOptionId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThirdChoiceOptionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FourthChoiceOptionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FourthChoiceOptionId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FourthChoiceOptionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SelectionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SelectionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearTermId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearTermId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearTermId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OptionsWebSite/Views/Choice/Delete.cshtml
@model DiplomaDataModel.Models.Choice

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Choice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstChoiceOptionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstChoiceOptionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondChoiceOptionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondChoiceOptionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThirdChoiceOptionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThirdChoiceOptionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FourthChoiceOptionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FourthChoiceOptionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SelectionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SelectionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YearTermId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearTermId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OptionsWebSite/Views/Choice/Details.cshtml
@model DiplomaDataModel.Models.Choice

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Choice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstChoiceOptionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Option1.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondChoiceOptionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Option2.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThirdChoiceOptionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Option3.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FourthChoiceOptionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Option4.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SelectionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SelectionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YearTermId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearTerm.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ChoiceId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OptionsWebSite/Views/Choice/Edit.cshtml
@model DiplomaDataModel.Models.Choice

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Choice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ChoiceId)

        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentFirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentLastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstChoiceOptionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstChoiceOptionId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstChoiceOptionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecondChoiceOptionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecondChoiceOptionId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecondChoiceOptionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThirdChoiceOptionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThirdChoiceOptionId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThirdChoiceOptionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FourthChoiceOptionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FourthChoiceOptionId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FourthChoiceOptionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SelectionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SelectionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearTermId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearTermId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearTermId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OptionsWebSite/Views/Choice/Index.cshtml
@model IEnumerable<DiplomaDataModel.Models.Choice>

@{
    ViewBag.Title = "Index";
}

<h2>Index </h2>

@section scripts {
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Highcharts-4.0.1/js/highcharts.js")" type="text/javascript"></script>

    <script type="text/javascript">
        var yeartermid = '@ViewBag.DefaultTerm';
        $(document).ready(function () {

            $("#yeartermResult").load('@(Url.Action("GenerateReportPartial", "Choice", null, Request.Url.Scheme))?yeartermid=' + yeartermid);
            $("#chartResult").load('@(Url.Action("GenerateChartPartial", "Choice", null, Request.Url.Scheme))?yeartermid=' + yeartermid);

            $("#yearTermSelected").change(function () {

                yeartermid = $("#yearTermSelected").val();
                $("#yeartermResult").load('@(Url.Action("GenerateReportPartial", "Choice", null, Request.Url.Scheme))?yeartermid=' + yeartermid);
                $("#chartResult").load('@(Url.Action("GenerateChartPartial", "Choice", null, Request.Url.Scheme))?yeartermid=' + yeartermid);

            });
        });
    </script>
}

@Html.ActionLink("Modify Student Choices", "Modify")

<div>
    <h3>Generate A Detailed Report</h3>
    @Html.Label("Select a term")
    @Html.Action("YearTermSelect", "Choice")

</div>

<div id="yeartermResult"></div>
<br />
<div id="chartResult"></div>

<div id="loadingDisplay" style="display: none">
    <img src="@Url.Content("~/Content/Images/ajax-loader.gif")"
         alt="loading image" />
</div>

OptionsWebSite/Views/Choice/Modify.cshtml
@model IEnumerable<DiplomaDataModel.Models.Choice>

@{
    ViewBag.Title = "Modify";
}

<h2>Modify</h2>
<p style="font-style:italic">Update or delete current student choices</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StudentId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StudentFirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StudentLastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstChoiceOptionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SecondChoiceOptionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThirdChoiceOptionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FourthChoiceOptionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SelectionDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearTermId)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StudentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudentFirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudentLastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Option1.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Option2.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Option3.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Option4.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SelectionDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YearTerm.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ChoiceId }) |
                @Html.ActionLink("Details", "Details", new { id = item.ChoiceId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ChoiceId })
            </td>
        </tr>
    }

</table>

OptionsWebSite/Views/Choice/_ChartReportPartial.cshtml
@model DotNet.Highcharts.Highcharts

@section Scripts {

    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Highcharts-4.0.1/js/highcharts.js")" type="text/javascript"></script>

}

@(Model)

OptionsWebSite/Views/Choice/_DetailReportPartial.cshtml
@model IEnumerable<DiplomaDataModel.Models.Choice>

@{ int yearterm = ViewBag.Message;}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StudentId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StudentFirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StudentLastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstChoiceOptionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SecondChoiceOptionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThirdChoiceOptionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FourthChoiceOptionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SelectionDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearTermId)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.YearTermId == yearterm)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StudentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudentFirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudentLastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Option1.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Option2.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Option3.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Option4.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SelectionDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YearTerm.Description)
            </td>
        </tr>
        }
    }

</table>

OptionsWebSite/Views/Choice/_YearTermSelectPartial.cshtml
@model DiplomaDataModel.Models.YearTerm

@Html.DropDownListFor(model => model.Term, ViewBag.YearTermList as SelectList, 
    new { id="yearTermSelected", @class = "form-control", Style = "width: 300px" })